### ISSUE TITLE
Update to v1.6.0

### ISSUE THREAD

**Issue by llaville** [creativeprojects/webgrind.docker#1]
Hello,

New release https://github.com/jokkedk/webgrind/releases/tag/v1.6.0 add compatibility with PHP 7 and add performance improvements.

It would be great to support it as new tag and of course the `latest` tag.

What do you think about it ?

**Comment by llaville** [comment]
Hello,
The latest tag was updated few hours ago, but still used the version 1.5.0.
Did you think to update it to 1.6.0 ?

**Comment by llaville** [comment]
is this project still maintened ?

**Comment by creativeprojects** [comment]
Hey! I'm not sure why I haven't got a notification. Apparently this project does not send any notification on opening/commenting on an issue.

Well I'm sorry about that. I'll update 1.6.0 :)

**Comment by creativeprojects** [comment]
Update Debian 10, php 7.3, webgrind 1.7.0
